import type { Metadata, Viewport } from "next";
import { Geist } from "next/font/google";
import { JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Heartbeat from "@/app/components/Heartbeat";
import NativePushRouter from "@/app/components/NativePushRouter";
import AirlockDeepLinkRouter from "@/app/components/AirlockDeepLinkRouter";
import ToastProvider from "@/app/components/ToastProvider";
import AppLockLoader from "@/app/components/AppLockLoader";
import LocaleCookieSync from "@/app/components/LocaleCookieSync";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { cookies } from "next/headers";
import { auth } from "@/lib/auth";
import { isValidLocale } from "@/lib/constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

// Beta-Instanz kennzeichnet sich per INSTANCE_LABEL (nur in der Beta-.env gesetzt) — eigener
// Name, eigenes App-Icon und rotes Theme, damit sich die iPhone-Home-App und die Optik klar
// von Prod abheben. Prod setzt die Variable nicht → unveraendert.
const IS_BETA = process.env.INSTANCE_LABEL === "BETA";

export async function generateMetadata(): Promise<Metadata> {
  const title = IS_BETA ? "KG Tracker BETA" : "KG Tracker";
  return {
    title,
    description: "Keuschheitsgürtel Tracking",
    manifest: "/manifest.webmanifest",
    appleWebApp: {
      capable: true,
      statusBarStyle: "black-translucent",
      title,
    },
    icons: {
      icon: IS_BETA ? "/icon-beta.svg" : "/icon.svg",
      apple: IS_BETA ? "/icon-192-beta.png" : "/icon-192.png",
    },
  };
}

export function generateViewport(): Viewport {
  return {
    width: "device-width",
    initialScale: 1,
    viewportFit: "cover",
    themeColor: IS_BETA ? "#ef4444" : "#111827",
  };
}

// iOS splash screen definitions (generated by scripts/generate-splash.mjs)
const splashScreens = [
  { w: 320, h: 568, r: 2, src: "/splash/splash-640x1136.png" },
  { w: 375, h: 667, r: 2, src: "/splash/splash-750x1334.png" },
  { w: 414, h: 736, r: 3, src: "/splash/splash-1242x2208.png" },
  { w: 375, h: 812, r: 3, src: "/splash/splash-1125x2436.png" },
  { w: 414, h: 896, r: 2, src: "/splash/splash-828x1792.png" },
  { w: 414, h: 896, r: 3, src: "/splash/splash-1242x2688.png" },
  { w: 360, h: 780, r: 3, src: "/splash/splash-1080x2340.png" },
  { w: 390, h: 844, r: 3, src: "/splash/splash-1170x2532.png" },
  { w: 428, h: 926, r: 3, src: "/splash/splash-1284x2778.png" },
  { w: 393, h: 852, r: 3, src: "/splash/splash-1179x2556.png" },
  { w: 430, h: 932, r: 3, src: "/splash/splash-1290x2796.png" },
  { w: 810, h: 1080, r: 2, src: "/splash/splash-1620x2160.png" },
  { w: 820, h: 1180, r: 2, src: "/splash/splash-1640x2360.png" },
  { w: 1024, h: 1366, r: 2, src: "/splash/splash-2048x2732.png" },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const session = await auth();
  const sessionUserId = (session?.user as { id?: string } | undefined)?.id ?? null;

  // Cross-device adoption: if this browser has no locale cookie yet but the account has a stored
  // language, adopt it once. Guarded on cookie-absence (not mismatch) so it never fights a choice
  // the user just made on this device while the JWT still carries the previous value.
  const hasLocaleCookie = (await cookies()).has("locale");
  const sessionLocale = (session?.user as { locale?: string } | undefined)?.locale;
  const localeToAdopt = !hasLocaleCookie && isValidLocale(sessionLocale) ? sessionLocale : null;

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        {/* Prevent iOS WebKit from auto-linking phone numbers / dates / addresses
            — those DOM mutations happen before React hydration and cause #418 */}
        <meta name="format-detection" content="telephone=no, date=no, address=no, email=no" />
        {/* iOS splash screens — portrait only */}
        {splashScreens.map(({ w, h, r, src }) => (
          <link
            key={src}
            rel="apple-touch-startup-image"
            href={src}
            media={`(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`}
          />
        ))}
      </head>
      <body className={`${geistSans.variable} ${jetbrainsMono.variable} antialiased`} suppressHydrationWarning>
        {IS_BETA && (
          <>
            <div aria-hidden="true" style={{ position: "fixed", inset: 0, border: "4px solid #ef4444", pointerEvents: "none", zIndex: 2147483647 }} />
            <div aria-hidden="true" style={{ position: "fixed", top: "calc(env(safe-area-inset-top, 0px) + 4px)", left: "50%", transform: "translateX(-50%)", background: "#ef4444", color: "#fff", fontSize: "11px", fontWeight: 700, letterSpacing: "1.5px", padding: "2px 12px", borderRadius: "0 0 8px 8px", pointerEvents: "none", zIndex: 2147483647 }}>BETA</div>
          </>
        )}
        <NextIntlClientProvider messages={messages}>
          <ToastProvider>
            {localeToAdopt && <LocaleCookieSync locale={localeToAdopt} />}
            {children}
            <AppLockLoader />
            <Heartbeat buildDate={process.env.BUILD_DATE ?? "local"} initialUserId={sessionUserId ?? null} />
            <NativePushRouter />
            <AirlockDeepLinkRouter />
            <Script id="sw-register" strategy="afterInteractive">{`
              if ('serviceWorker' in navigator && window.location.hostname !== 'localhost') {
                navigator.serviceWorker.register('/sw.js').catch(function(err) {
                  console.warn('[SW] registration failed:', err);
                });
              }
              /* Das Badge wird NICHT mehr blind geräumt: es zählt seit v4.56.0 ungelesene
                 Nachrichten, und ein unbedingtes clearAppBadge() beim Start/Resume hätte es nach
                 dem ersten Blick in die App für immer gelöscht. Gesetzt wird es jetzt am Zustand,
                 in AppBadgeSync (Header). */
            `}</Script>
          </ToastProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
